package com.ht.dao;

import com.ht.vo.DicZhibiao;
import com.ht.vo.DicZhibiaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DicZhibiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIC_ZHIBIAO
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    int countByExample(DicZhibiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIC_ZHIBIAO
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    int deleteByExample(DicZhibiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIC_ZHIBIAO
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    int insert(DicZhibiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIC_ZHIBIAO
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    int insertSelective(DicZhibiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIC_ZHIBIAO
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    List<DicZhibiao> selectByExample(DicZhibiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIC_ZHIBIAO
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") DicZhibiao record, @Param("example") DicZhibiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIC_ZHIBIAO
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    int updateByExample(@Param("record") DicZhibiao record, @Param("example") DicZhibiaoExample example);
}