package com.ht.vo;

public class DicZhibiao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIC_ZHIBIAO.ID
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIC_ZHIBIAO.NAME
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIC_ZHIBIAO.UNIT
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIC_ZHIBIAO.GEOTYPE
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    private String geotype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIC_ZHIBIAO.ID
     *
     * @return the value of DIC_ZHIBIAO.ID
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIC_ZHIBIAO.ID
     *
     * @param id the value for DIC_ZHIBIAO.ID
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIC_ZHIBIAO.NAME
     *
     * @return the value of DIC_ZHIBIAO.NAME
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIC_ZHIBIAO.NAME
     *
     * @param name the value for DIC_ZHIBIAO.NAME
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIC_ZHIBIAO.UNIT
     *
     * @return the value of DIC_ZHIBIAO.UNIT
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIC_ZHIBIAO.UNIT
     *
     * @param unit the value for DIC_ZHIBIAO.UNIT
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIC_ZHIBIAO.GEOTYPE
     *
     * @return the value of DIC_ZHIBIAO.GEOTYPE
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    public String getGeotype() {
        return geotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIC_ZHIBIAO.GEOTYPE
     *
     * @param geotype the value for DIC_ZHIBIAO.GEOTYPE
     *
     * @mbggenerated Tue Oct 16 15:58:37 CST 2018
     */
    public void setGeotype(String geotype) {
        this.geotype = geotype == null ? null : geotype.trim();
    }
}